import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Configure Poppins font with desired weights and subsets
const poppinsSans = Poppins({
  weight: ["400", "500", "600", "700"], // Regular, Medium, Semi-bold, Bold
  variable: "--font-poppins-sans",
  subsets: ["latin"],
});

// Use Poppins for monospace as well, with a lighter weight for distinction
const poppinsMono = Poppins({
  weight: ["300"], // Lighter weight for monospace-like appearance
  variable: "--font-poppins-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "dazzle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${poppinsMono.variable} antialiased dark:bg-gray-900`}
      >
        {children}
      </body>
    </html>
  );
}
